# Generated by Django 3.1.3 on 2021-04-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VocabCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocab_word', models.CharField(max_length=30)),
                ('vocab_pos', models.CharField(choices=[('ADJ', 'Adjective'), ('N', 'Noun'), ('V', 'Verb')], default='ADJ', max_length=10)),
                ('vocab_meaning', models.TextField()),
                ('vocab_sentence', models.TextField()),
                ('vocab_synonyms', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
