# Generated by Django 3.1.3 on 2021-04-15 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocabTrainer', '0003_auto_20210415_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnDeck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_learnt', models.BooleanField(default=False)),
                ('word_count', models.IntegerField(blank=True, default=5)),
                ('word_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabTrainer.vocabcard')),
            ],
        ),
    ]
