# Generated by Django 3.1.3 on 2021-04-15 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabTrainer', '0004_learndeck'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabcard',
            name='time_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='vocabcard',
            name='vocab_synonyms',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
