# Generated by Django 3.1.3 on 2021-04-16 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabTrainer', '0005_auto_20210415_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocabcard',
            old_name='vocab_word_bookmarked',
            new_name='bookmarked',
        ),
        migrations.RenameField(
            model_name='vocabcard',
            old_name='vocab_learn',
            new_name='re_learn',
        ),
        migrations.RemoveField(
            model_name='vocabcard',
            name='time_added',
        ),
        migrations.AddField(
            model_name='vocabcard',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.date(2021, 4, 16)),
        ),
        migrations.AlterField(
            model_name='vocabcard',
            name='vocab_pos',
            field=models.CharField(choices=[('Adjective', 'Adjective'), ('Noun', 'Noun'), ('Verb', 'Verb')], default='Adjective', max_length=10),
        ),
        migrations.AlterField(
            model_name='vocabcard',
            name='vocab_synonyms',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
