# Generated by Django 3.1.3 on 2021-04-16 09:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vocabTrainer', '0006_auto_20210416_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabcard',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 16, 9, 19, 21, 269749, tzinfo=utc)),
        ),
    ]
