# Generated by Django 3.1.3 on 2021-04-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabTrainer', '0011_checkpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpoint',
            name='word_id',
            field=models.IntegerField(unique=True),
        ),
    ]
