# Generated by Django 3.1.3 on 2021-04-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabTrainer', '0012_auto_20210418_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpoint',
            name='word_id',
            field=models.IntegerField(),
        ),
    ]
