# Generated by Django 3.1.3 on 2021-04-19 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocabTrainer', '0013_auto_20210419_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.IntegerField()),
                ('word_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabTrainer.vocabcard')),
            ],
        ),
    ]
