# Generated by Django 3.1.3 on 2021-04-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabTrainer', '0015_auto_20210419_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabcard',
            name='set_number',
            field=models.IntegerField(default=0),
        ),
    ]
