# Generated by Django 3.1.3 on 2021-04-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabTrainer', '0016_vocabcard_set_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabcard',
            name='vocab_sentence',
            field=models.TextField(blank=True, null=True),
        ),
    ]
