# Generated by Django 3.1.3 on 2021-04-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabTrainer', '0017_auto_20210420_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabcard',
            name='set_number',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
