# Generated by Django 3.1.3 on 2021-04-21 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabTrainer', '0018_auto_20210420_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempDeck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_id', models.IntegerField()),
            ],
        ),
    ]
