# Generated by Django 3.1.3 on 2021-04-21 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabTrainer', '0019_tempdeck'),
    ]

    operations = [
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('count', models.IntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='checkPoint',
        ),
        migrations.RemoveField(
            model_name='learndeck',
            name='word_id',
        ),
        migrations.DeleteModel(
            name='Set',
        ),
        migrations.DeleteModel(
            name='LearnDeck',
        ),
    ]
