# Generated by Django 3.1.3 on 2021-04-21 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabTrainer', '0020_auto_20210421_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streak',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
