# Generated by Django 3.1.3 on 2021-04-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabTrainer', '0021_auto_20210421_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='streak',
            name='longest_streak',
            field=models.IntegerField(default=1),
        ),
    ]
